name: Workflow 1 - Email SANS PowerPoint (12 destinataires)

on:
  schedule:
    # Tous les jours à 8h00 heure de Paris (7h UTC en hiver)
    - cron: '0 7 * * *'

  # Permet un déclenchement manuel
  workflow_dispatch:

jobs:
  send-email-without-ppt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl matplotlib python-pptx selenium chromedriver-autoinstaller

    - name: Install Chrome and ChromeDriver
      run: |
        # Install Chrome
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

        # Check versions
        google-chrome --version
        chromedriver --version || echo "ChromeDriver not in PATH"

    - name: Download Excel file from SharePoint
      env:
        DISPLAY: :99
        SHAREPOINT_USERNAME: ${{ secrets.SHAREPOINT_USERNAME }}
        SHAREPOINT_PASSWORD: ${{ secrets.SHAREPOINT_PASSWORD }}
      run: |
        echo "=========================================="
        echo "  TÉLÉCHARGEMENT SHAREPOINT"
        echo "=========================================="
        sudo Xvfb -ac :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        sleep 2
        python download_robot.py
        if [ -f "NOUVEAU FAC PERSPECTIVIA.xlsx" ]; then
          echo "✅ Fichier téléchargé avec succès"
          ls -lh "NOUVEAU FAC PERSPECTIVIA.xlsx"
        else
          echo "❌ ERREUR: Fichier non téléchargé"
          exit 1
        fi

    - name: Generate data and checklists
      run: |
        echo "=========================================="
        echo "  GÉNÉRATION DES CHECKLISTS"
        echo "=========================================="
        python pt2.py
        echo ""
        echo "Vérification des fichiers générés:"
        ls -lh Checklist/*.xlsx

    - name: Send email WITHOUT PowerPoint (2 recipients - Pierre, Berfay)
      env:
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      run: |
        echo "=========================================="
        echo "  WORKFLOW 1: EMAIL SANS POWERPOINT"
        echo "  2 DESTINATAIRES:"
        echo "  - bisiaux.pierre@outlook.fr"
        echo "  - b.hunalp@rhreflex.com"
        echo "  Pièces jointes: 8 fichiers Excel checklist"
        echo "=========================================="
        python email_sender/send_report_without_ppt.py

    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: workflow1-rapport-${{ github.run_number }}
        path: |
          Checklist/*.xlsx
          NOUVEAU FAC PERSPECTIVIA.xlsx
        retention-days: 7
